    name: Send Daily Lucky Color Email

    on:
      workflow_dispatch: # 允许手动触发
      schedule:
        # 这里的 '0 23 * * *' 是UTC时间。
        # 北京时间是 UTC+8，所以UTC 23:00 就是北京时间第二天早上7:00。
        - cron: '0 23 * * *'

    jobs:
      build-and-send:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.9'

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install lunar_python

          - name: Run Python script to send email
            env:
              SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
              APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
            run: python main.py
